; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Launcher"
#define MyAppVersion "1.0"
#define MyAppPublisher "NikasWolf, Sonar"
#define MyAppExeName "Launcher.exe"
#define MyAppAssocName "My Program File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A2256A09-BF16-4ADF-897C-1CECD015CE09}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\My Program
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DefaultGroupName=My Program
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=LauncherSetup
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "X:\Cods\LauncherGit\Launcher\Launcher\publish_fix\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "X:\Cods\LauncherGit\Launcher\Launcher\publish_fix\av_libglesv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "X:\Cods\LauncherGit\Launcher\Launcher\publish_fix\games.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "X:\Cods\LauncherGit\Launcher\Launcher\publish_fix\Launcher.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "X:\Cods\LauncherGit\Launcher\Launcher\publish_fix\Launcher.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "X:\Cods\LauncherGit\Launcher\Launcher\publish_fix\libHarfBuzzSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "X:\Cods\LauncherGit\Launcher\Launcher\publish_fix\libHarfBuzzSharp.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "X:\Cods\LauncherGit\Launcher\Launcher\publish_fix\libSkiaSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "X:\Cods\LauncherGit\Launcher\Launcher\publish_fix\libSkiaSharp.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "X:\Cods\LauncherGit\Launcher\Launcher\publish_fix\user_games.json"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

